/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package org.icgc_argo.workflow_graph_lib.schema;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class GraphRun extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5115707910350237644L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"GraphRun\",\"namespace\":\"org.icgc_argo.workflow_graph_lib.schema\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"UUID\"},{\"name\":\"runId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GraphRun> ENCODER =
      new BinaryMessageEncoder<GraphRun>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GraphRun> DECODER =
      new BinaryMessageDecoder<GraphRun>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GraphRun> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GraphRun> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GraphRun> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GraphRun>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GraphRun to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GraphRun from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GraphRun instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static GraphRun fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String runId;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public GraphRun() {}

  /**
   * All-args constructor.
   *
   * @param id The new value for id
   * @param runId The new value for runId
   */
  public GraphRun(java.lang.String id, java.lang.String runId) {
    this.id = id;
    this.runId = runId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return id;
      case 1:
        return runId;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        id = value$ != null ? value$.toString() : null;
        break;
      case 1:
        runId = value$ != null ? value$.toString() : null;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   *
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   *
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'runId' field.
   *
   * @return The value of the 'runId' field.
   */
  public java.lang.String getRunId() {
    return runId;
  }

  /**
   * Sets the value of the 'runId' field.
   *
   * @param value the value to set.
   */
  public void setRunId(java.lang.String value) {
    this.runId = value;
  }

  /**
   * Creates a new GraphRun RecordBuilder.
   *
   * @return A new GraphRun RecordBuilder
   */
  public static org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder newBuilder() {
    return new org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder();
  }

  /**
   * Creates a new GraphRun RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new GraphRun RecordBuilder
   */
  public static org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder newBuilder(
      org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder other) {
    if (other == null) {
      return new org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder();
    } else {
      return new org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder(other);
    }
  }

  /**
   * Creates a new GraphRun RecordBuilder by copying an existing GraphRun instance.
   *
   * @param other The existing instance to copy.
   * @return A new GraphRun RecordBuilder
   */
  public static org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder newBuilder(
      org.icgc_argo.workflow_graph_lib.schema.GraphRun other) {
    if (other == null) {
      return new org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder();
    } else {
      return new org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder(other);
    }
  }

  /** RecordBuilder for GraphRun instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GraphRun>
      implements org.apache.avro.data.RecordBuilder<GraphRun> {

    private java.lang.String id;
    private java.lang.String runId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GraphRun instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(org.icgc_argo.workflow_graph_lib.schema.GraphRun other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'id' field.
     *
     * @return The value.
     */
    public java.lang.String getId() {
      return id;
    }

    /**
     * Sets the value of the 'id' field.
     *
     * @param value The value of 'id'.
     * @return This builder.
     */
    public org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'id' field has been set.
     *
     * @return True if the 'id' field has been set, false otherwise.
     */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'id' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'runId' field.
     *
     * @return The value.
     */
    public java.lang.String getRunId() {
      return runId;
    }

    /**
     * Sets the value of the 'runId' field.
     *
     * @param value The value of 'runId'.
     * @return This builder.
     */
    public org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder setRunId(
        java.lang.String value) {
      validate(fields()[1], value);
      this.runId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'runId' field has been set.
     *
     * @return True if the 'runId' field has been set, false otherwise.
     */
    public boolean hasRunId() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'runId' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow_graph_lib.schema.GraphRun.Builder clearRunId() {
      runId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GraphRun build() {
      try {
        GraphRun record = new GraphRun();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.runId =
            fieldSetFlags()[1] ? this.runId : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GraphRun> WRITER$ =
      (org.apache.avro.io.DatumWriter<GraphRun>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GraphRun> READER$ =
      (org.apache.avro.io.DatumReader<GraphRun>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeString(this.id);

    out.writeString(this.runId);
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.runId = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.id = in.readString();
            break;

          case 1:
            this.runId = in.readString();
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
